name: Jens Ingebretsen
favicon: null
layout_spectrum: 0.74224
typography_spectrum: 0.57469
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#23281e'
    - '#fffbf8'
    - '#a6ae38'
    - '#fe5f7d'
    - '#a51837'
  brandStrength: 0.4375
  lightness: 0.02603905857540667
  saturation: 0.7563263499177992
  rhythmicContrast: 0.19032729812897742
purpose: []
